### ISSUE TITLE
Shibd also doesn't like existing lock files

### ISSUE THREAD

**Issue by jschilperoord** [Unicon/shibboleth-sp-dockerized#1]
In my customizations I also included a:

`rm -f /var/lock/subsys/shibd`

Somehow this lock file existed and the container didn't startup correctly. Maybe add it to your image as well ?

**Comment by jtgasper3** [comment]
Thanks for the report.  Did stop and start the same container? That probably did it. In my quick testing, I've cleaning each time as I used this image as a base in another project.

I'll get that added in shortly.

**Comment by jtgasper3** [comment]
Commit ba2b28a5ea9231dbc45cb2e3f5426b4997250563. It's rebuilding now.

Please feel free to reopen if this does not work as expected when you pull the updated image.
