### ISSUE TITLE
Permissions on /etc/shibboleth/shibd-redhat seem to be wrong.

### ISSUE THREAD

**Issue by hughbarronjohnson** [Unicon/shibboleth-sp-dockerized#12]
Shibd is not executing due to shibd-redhat not being executable.   On startup the container gives:  

/usr/local/bin/httpd-shibd-foreground: line 7: /etc/shibboleth/shibd-redhat: Permission denied

If I add a  "RUN chmod +x /etc/shibboleth/shibd-redhat"  to Dockerfile, it starts up normally.

**Comment by jtgasper3** [comment]
Thanks for providing a PR to fix this.

**Comment by hughbarronjohnson** [comment]
Anytime!  Glad to help.

**Comment by mertmetin** [comment]
Worked! Thank you.
