### ISSUE TITLE
repo opensuse

### ISSUE THREAD

**Issue by cata86** [Unicon/shibboleth-sp-dockerized#4]
The opensuse repositories are no longer available.
The build fail always.
You could use an alternative repository in the DockerFile

http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo

**Comment by jtgasper3** [comment]
Hi @cata86,

I just tested a build and it worked fine for me. Browsed to `http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo` and it resolved just fine. I kicked off the automated build on Docker Hub just now and it ran fine. 

Maybe a transitive issue?
