### ISSUE TITLE
Is /usr/local/apache2/logs/httpd.pid the wrong PID file?

### ISSUE THREAD

**Issue by Swandog** [Unicon/shibboleth-sp-dockerized#5]
I've been getting errors saying that httpd is already running, and the server shuts down. I looked at httpd-shibd-foreground, and there's a `rm -f /usr/local/apache2/logs/httpd.pid` command. But that file looks like it's for an apache base, not CentOS; wouldn't CentOS be in /etc/httpd? FWIW, I don't see /usr/local/apache2 in the container at all.

And FWIW, when I run the container and it runs, the PID file isn't there either; it's in /run/httpd

I'm a little new to apache which is why I didn't just fork and submit a PR myself.

**Comment by jtgasper3** [comment]
You are probably right. I work with httpd on various distros, and probably goofed that. Please do submit a PR and I'll get it pulled in.
