### ISSUE TITLE
Publish Docker image 3.0.2

### ISSUE THREAD

**Issue by sebastianwoinar** [Unicon/shibboleth-sp-dockerized#7]
Can you please release this Docker image?

`unicon/shibboleth-sp:latest` is still `unicon/shibboleth-sp:3.0.1`

**Comment by jtgasper3** [comment]
@sebastianwoinar Thanks for the report. 

I've kicked off the build again and it appears to have rebuilt with the correct SP version. Please do a `docker pull` and confirm that you are at `3.0.2`.
