### ISSUE TITLE
Dynamic metadata is not downloaded

### ISSUE THREAD

**Issue by yasvanth** [Unicon/shibboleth-sp-dockerized#8]
Hi,
I have an issue when setting Metadata Provider from static to dynamic. no metadata is downloaded to `/var/cache/shibboleth`, this applies event when I set MDQ.

curl libraries and permission are correct. 

Best,
Yash

**Comment by jtgasper3** [comment]
I'll have to take a look. I don't have an MDQ server setup to test with.

Are any errors reported in the log files/streams?

**Comment by yasvanth** [comment]
Hi John,
There was not errors regarding Medata download in the logs, I tried both dynamic metadata and MDQ but no luck. If you require any futher information please do let me know.

Best,
Yash

Get Outlook for Android

________________________________

**Comment by yasvanth** [comment]
Hi John,
The issue has been fixed, The remote metadata (Edugate) has higher chiper suites  which is not supported by curl version 7.29 in centos 7, Upgrading to version 7.61 has fixed the issue. 

Thanks for your time.

Best,
Yash

**Comment by jtgasper3** [comment]
Thanks for the report back.
